language: node_js
node_js:
  - 8
  - 6
  - 4
script:
  - npm run coverage
  - npm run report
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: ZvmFjqGQZfVvIUsybIMOVdZ+KD26ZC8sR7iB3Fije8iU+V+DwG55qFAlT+k2AuW0AzILvE0nucO6Qtvp800jaVUjCOaGcfdkBVzTyoQgDZMJ+jRxt/B84o3SpudkWJ9YIxQ6zPMNvMkia375a/ppKnM2Ha4kWafXxJC1hj5VJhnpZID4XKC0qJvfzle33ai9WCmmK/9Rbu/lhJp9ex3awdONHUY54bsyQPV1aC9VOFQYrLLYhoW1fTPNGYLJF3KsPTmnn9rtXkPxrcO//mrEK4MQFVOS5fN7dAXDETvMRXw+MEAPfes/X5YTxLNBqF+IY0hpI7hil2hGHoBRDAVRsbbTAkkcZgaV0xbIL7Tws0KKgFfahmMPZfp1kzHxco4YgCqpapNx2AA90ZyOxcqEKTFlhKywY7hg+F0EWELxu80fDGtuWjnbbUpPh7jyCf2oe+hGZYSNK3xn9jSiz3+T6oRHtZOxxfSTDLoynWtkb6AXIwIV4mFwrSX5nOvk6DVegGdxKpLyUqjv3OfyS8CPtebbOKX4bTWtchU/UULrCQ0ujcSJV7PWupeoR39Vfk9s4A8MTYnA+a9f+i+oQfk6QEklfGY+3IG8E2al7xQ/AsqtyBQkKyurl4qq5A6d37/sufBoDIwFmq7eBOUQYdYwRV1qUF+ZJ0nWdV2gWtuSdeU=
  on:
    tags: true
    node: 8
